services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server-http

  web:
    container_name: web
    build: ./angular/
    networks:
      - server-http

networks:
  server-http:
    external: true