FROM --platform=linux/amd64 node:23.5 AS build

WORKDIR /app

COPY app/ .

RUN npm install \
    && npx ng build

FROM nginx:alpine

COPY --from=build /app/dist/app/browser /usr/share/nginx/html

EXPOSE 80